### ISSUE TITLE
optimize_bus gives low value

### ISSUE THREAD

**Issue by nickolasclarke** [nickolasclarke/dispatch#22]
`optimize_bus_distribution.py` currently gives a very low number (99 buses req. to service AC transit, for example)

**Comment by r-barnes** [comment]
When I disable opportunistic charging, I get 319 buses for Minneapolis, which is on the right order of magnitude.

I think there's an issue with opportunistic charging here:
```
charge_time * (self.charging_rate / 60)
```
`charge_time` should be in seconds and `charging_rate` is probably `kWh/h` or something, so it should be divided by 3600 instead of 60.

**Comment by r-barnes** [comment]
Since units are turning out to be an issue, we could consider using [Pint](https://pint.readthedocs.io/en/0.9/).

**Comment by r-barnes** [comment]
Closing since we've switched bus counting systems.
